### ISSUE TITLE
XPress 404 not setting 404 status

### ISSUE THREAD

**Issue by kylerc** [Audentio/xpress-issues#465] opened 2019-02-06 14:57 UTC
I think just needs ```status_header(404);
nocache_headers();``` at the end of 404.php in wordpress theme, but you'll want to verify.

**Comment by JakeBooher** [comment] 2019-02-07 22:00
We're going to want a cleaner solution than this, should be possible to pass the response code to XenForo so it renders with the correct code

**Comment by LukasWieditz** [comment] 2019-02-11 15:07
Duplicate of #460

**Closed as completed by LukasWieditz** 2019-02-11 15:07 UTC
