### ISSUE TITLE
Re-Promote Xenforo Thread Issue

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#257] opened 2018-09-04 12:11 UTC
When I delete permanently an article at wordpress which is created from an existing xenforo thread, I can not re-promote the same xenforo thread again (due to the missing "Promote" option at XF Thread menu)

**Comment by ichpen** [comment] 2018-09-13 19:16
Did this make the pre-release PL5? Because I see it's broken still.

**Comment by LukasWieditz** [comment] 2018-09-14 08:03
It won't fix for old articles.

**Comment by ichpen** [comment] 2018-09-14 13:17
> It won't fix for old articles.

This was a *new* article. I promoted a thread to article, deleted article in WP, tried to promote same thread again. This is on PL5. Not sure if this usecase is supported but behaviour is as such.

**Comment by LukasWieditz** [comment] 2018-09-14 14:08
I'll take a look. Definitely not intended for new articles. Did you actually delete the article inside the trashbin? If you only move it to trash, the link will remain.

**Comment by ichpen** [comment] 2018-09-14 14:32
OK here's what actually happens, bit of weirdness:
As admin:
1. Create thread in XF
2. Promote to Article
3. Delete Article/Post in WP (trash/soft delete)
4. Thread in XF cannot be promoted
5. Hard delete in WP (empty trash)
6. Thread in XF is automatically locked BUT is promotable

There's something not quite right there but it sort of works with some fudging. I guess if Xpress didn't lock the thread after hard delete in WP it would be ok.

@LukasWieditz

**Comment by LukasWieditz** [comment] 2018-09-17 08:56
That's the intended behavior. As long as you don't really delete the article in WP, we don't expect the link to go away, and when you delete it, we automatically lock the thread.

**Closed as completed** 2018-09-17 09:27 UTC
Labels: bug

**Comment by doublespaces** [comment] 2019-01-06 04:28
I might add a closely related issue:
Trying to permanently delete a blog post after the thread has already been deleted results in an error. The thread ID must be changed to an existing thread and then it may be deleted. This also closes the donor thread and must be re-opened if that wasn't intended.
