### ISSUE TITLE
Masonry overlapping (needs to be recalculated)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#426] opened 2019-01-27 02:13 UTC
`listofarticles.layout()` is what you want. Perhaps a settime out is best

**Comment by LukasWieditz** [comment] 2019-01-28 11:43
We don't want to constantly rebuild the whole masonry list. When is this issue happening? Randomly after some time? Or when you resize the browser?

**Comment by LukasWieditz** [comment] 2019-02-13 10:19
Duplicate of #458

**Closed as completed by LukasWieditz** 2019-02-13 10:19 UTC
