### ISSUE TITLE
Logout from wordppress redirect to Xenforo without logout

### ISSUE THREAD

**Issue by maxinikaido** [Audentio/xpress-issues#586] opened 2019-09-12 19:12 UTC
Hi,

When trying to logout from wordpress, it redirects me to xenforo and without logout.
So, i can return to wordpress still logged.

Can you help?

**Comment by LukasWieditz** [comment] 2019-09-12 19:26
Duplicate of #570

**Closed as completed by LukasWieditz** 2019-09-12 19:26 UTC
Labels: duplicate
