### ISSUE TITLE
Error when attempting to create a user promotion

### ISSUE THREAD

**Issue by daltonp** [Audentio/xpress-issues#581] opened 2019-08-07 18:44 UTC
```
GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php at line 186
GuzzleHttp\Handler\CurlFactory::createRejection() in src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php at line 149
GuzzleHttp\Handler\CurlFactory::finishError() in src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php at line 102
GuzzleHttp\Handler\CurlFactory::finish() in src/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php at line 43
GuzzleHttp\Handler\CurlHandler->__invoke() in src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php at line 28
GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() in src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php at line 51
GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() in src/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php at line 37
GuzzleHttp\PrepareBodyMiddleware->__invoke() in src/vendor/guzzlehttp/guzzle/src/Middleware.php at line 30
GuzzleHttp\Middleware::GuzzleHttp\{closure}() in src/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php at line 54
GuzzleHttp\RedirectMiddleware->__invoke() in src/vendor/guzzlehttp/guzzle/src/Middleware.php at line 60
GuzzleHttp\Middleware::GuzzleHttp\{closure}() in src/vendor/guzzlehttp/guzzle/src/HandlerStack.php at line 67
GuzzleHttp\HandlerStack->__invoke() in src/vendor/guzzlehttp/guzzle/src/Client.php at line 277
GuzzleHttp\Client->transfer() in src/vendor/guzzlehttp/guzzle/src/Client.php at line 125
GuzzleHttp\Client->requestAsync() in src/vendor/guzzlehttp/guzzle/src/Client.php at line 131
GuzzleHttp\Client->request() in src/vendor/guzzlehttp/guzzle/src/Client.php at line 89
GuzzleHttp\Client->__call() in src/addons/ThemeHouse/Core/Http/HttpClient/20181220.php at line 12
ThemeHouse\Core\Http\HttpClient->simpleGet() in src/addons/ThemeHouse/XLink/RemoteHandler/Traits/APICall.php at line 64
ThemeHouse\XPress\RemoteHandler\Usergroup->callAPI() in src/addons/ThemeHouse/XPress/RemoteHandler/Usergroup.php at line 23
ThemeHouse\XPress\RemoteHandler\Usergroup->getRemoteUserGroups() in src/addons/ThemeHouse/XLink/Admin/Controller/Promotion.php at line 97
ThemeHouse\XLink\Admin\Controller\Promotion->promotionAddEdit() in src/addons/ThemeHouse/XLink/Admin/Controller/Promotion.php at line 81
ThemeHouse\XLink\Admin\Controller\Promotion->actionAdd() in src/XF/Mvc/Dispatcher.php at line 321
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 244
XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 100
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 50
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2178
XF\App->run() in src/XF.php at line 390
XF::runApp() in admin.php at line 13
```

**Comment by LukasWieditz** [comment] 2019-08-08 15:53
Duplicate of #575

**Closed as completed by LukasWieditz** 2019-08-08 15:53 UTC
Labels: duplicate
