### ISSUE TITLE
Disabling XLink and widgets still are an option

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xpress-issues#361] opened 2018-12-20 20:24 UTC
When I disable XLink and XPress, I still have the option for the widgets I set up in widgets but then when I select one, it breaks the page on the forum where I put it. Nothing shows up. It is fixed once I enable it again. I shouldn't be able to choose the widget if it is disabled.

**Comment by LukasWieditz** [comment] 2019-01-08 10:16
Duplicate of #373

**Closed as completed by LukasWieditz** 2019-01-08 10:16 UTC
Labels: bug
