### ISSUE TITLE
[TH] XPress PL 5 - Not escaping categories/sub-navigation text

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#270] opened 2018-09-13 19:08 UTC
Think I had a ticket on this long ago but you may have missed it. In latest PL5 I still see categories not escaped correctly as per sreenshot.

![not-escaped](https://user-images.githubusercontent.com/5346876/45509937-d7cec680-b766-11e8-8f62-5f8ceb78927b.png)

**Comment by LukasWieditz** [comment] 2018-09-13 19:23
Well technically it is escaping... too much. We'll get that fixed, thanks.

**Comment by ichpen** [comment] 2018-09-13 19:58
Yes lol that it is.

**Comment by LukasWieditz** [comment] 2018-09-17 08:15
I find myself unable to reproduce this on a stock WP with only XPress installed.

**Comment by ichpen** [comment] 2018-09-17 10:45
You can add a wp post category with an ampersand? Not sure what to tell you as it's specific to the xpress/wp page. I can give you access if you want.

**Comment by LukasWieditz** [comment] 2018-09-17 13:38
Yeah, it's working fine. I remember us having this problem earlier (around PL3 or so), but we fixed it back then.

![jdd3tnr](https://user-images.githubusercontent.com/38475165/45626372-b257fa80-ba8f-11e8-9667-5136a506361e.png)

**Comment by ichpen** [comment] 2018-09-17 14:10
> Yeah, it's working fine. I remember us having this problem earlier (around PL3 or so), but we fixed it back then.
> 
> ![jdd3tnr](https://user-images.githubusercontent.com/38475165/45626372-b257fa80-ba8f-11e8-9667-5136a506361e.png)

So you just gave me an idea and this seems to be specific to UIX 2. Default theme doesn't do this.

Tagging @Ian-Hitt maybe here for a helping hand...

**Comment by LukasWieditz** [comment] 2018-09-17 14:11
Is it working for you on default style then?

I for one can't reproduce it on stock UI.X either unfortunately.

![tvrpxuw](https://user-images.githubusercontent.com/38475165/45628441-60fe3a00-ba94-11e8-90a7-ae739957f2ae.png)

**Comment by ichpen** [comment] 2018-09-17 14:12
> Is it working for you on default style then?
> 
> I for one can't reproduce it on stock UI.X either unfortunately.
> 
> ![tvrpxuw](https://user-images.githubusercontent.com/38475165/45628441-60fe3a00-ba94-11e8-90a7-ae739957f2ae.png)

Yes working on default but switching to UIX 2.0.7.2 breaks it.

**Comment by LukasWieditz** [comment] 2018-09-17 14:13
Hm, it'll probably be fixed with the 2.0.10 update then.

**Comment by ichpen** [comment] 2018-09-17 14:15
> Hm, it'll probably be fixed with the 2.0.10 update then.

Hopefully. Guess you can close this as it's not an xpress issue. Thanks for checking.

**Comment by LukasWieditz** [comment] 2018-09-17 14:17
Post it over in the https://github.com/Audentio/xf2theme-issues/issues repo if it turns out to not be fixed.

**Closed as completed by LukasWieditz** 2018-09-17 14:17 UTC
Labels: Invalid
