### ISSUE TITLE
GuzzleHttp\Exception\RequestException

### ISSUE THREAD

**Issue by daltonp** [Audentio/xpress-issues#574] opened 2019-07-24 17:08 UTC
Reported by xPreswa on ticket #14570
```
#0 src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 src/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 src/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 src/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 src/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(54): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 src/vendor/guzzlehttp/guzzle/src/Middleware.php(60): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 src/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 src/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 src/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 src/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array)
#13 src/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('get', '/api.php?action...', Array)
#14 src/addons/ThemeHouse/Core/Http/HttpClient/20181220.php(12): GuzzleHttp\Client->__call('get', Array)
#15 src/addons/ThemeHouse/XLink/RemoteHandler/Traits/APICall.php(64): ThemeHouse\Core\Http\HttpClient->simpleGet('/api.php?action...', Array)
#16 src/addons/ThemeHouse/XWiki/RemoteHandler/Usergroup.php(18): ThemeHouse\XWiki\RemoteHandler\Usergroup->callAPI('xwiki-usergroup...')
#17 src/addons/ThemeHouse/XLink/Admin/Controller/Promotion.php(97): ThemeHouse\XWiki\RemoteHandler\Usergroup->getRemoteUserGroups()
#18 src/addons/ThemeHouse/XLink/Admin/Controller/Promotion.php(81): ThemeHouse\XLink\Admin\Controller\Promotion->promotionAddEdit(Object(ThemeHouse\XLink\Entity\Promotion))
#19 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\XLink\Admin\Controller\Promotion->actionAdd(Object(XF\Mvc\ParameterBag))
#20 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\XLin...', 'Add', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\XLink\Admin\Controller\Promotion), NULL)
#21 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\XLink\Admin\Controller\Promotion), NULL)
#22 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#23 src/XF/App.php(2178): XF\Mvc\Dispatcher->run()
#24 src/XF.php(390): XF\App->run()
#25 admin.php(13): XF::runApp('XF\\Admin\\App')
#26 {main}
```

**Comment by LukasWieditz** [comment] 2019-08-08 16:18
Duplicate of #575

**Closed as completed by LukasWieditz** 2019-08-08 16:18 UTC
Labels: duplicate
