### ISSUE TITLE
WP Category Navigation bar Responsive Problem

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#189] opened 2018-07-20 20:51 UTC
As you can see at attached, while browsing by tablet (IPAD 2), if we define and use lots of categories,  category navigation bar is not responsive.

https://postimg.cc/image/d8tby8iwx/

**Comment by LukasWieditz** [comment] 2018-08-02 11:07
@Ian-Hitt this is working fine on my dev environment. Iirc, the fix for that was in UI.X not in XPress? Has that been pushed live yet?

**Comment by mikecreuzer** [comment] 2018-08-03 14:49
Would like this patched as this would cause mobile bugs for anyone with more than say 10 categories. Just need same markup as forums, a copy and paste thing.

**Comment by LukasWieditz** [comment] 2018-08-03 15:20
This needs to be done in UI.X, and stated above, I'm pretty sure it's already fixed there, but just hasn't been published yet. I cannot reproduce it on my dev anymore.

**Comment by LukasWieditz** [comment] 2018-08-03 15:26
Moved it over to the other repo and marked it as solved there.

**Closed as completed by LukasWieditz** 2018-08-03 15:26 UTC
Labels: duplicate
